version: Userprovider002-git-update
spring:
  application:
    name: Userprovider
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/boot002
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka,http://localhost:8889/eureka

    show-sql: true
server:
  port: 9005

