version: Userprovider002-git-u
vv: uu
spring:
  application:
    name: Userprovider
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://db1:3306/boot002
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true


